import axios from "axios";
import { GetServerSideProps, GetServerSidePropsContext } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { loadProgressBar } from "x-axios-progress-bar";
import "x-axios-progress-bar/dist/nprogress.css";

// https://github.com/mszkb/progress-bar-4-axios#readme
loadProgressBar();
interface Props {
  region: string;
  id: string;
}

export default function Post(props: Props) {
  const [response, setResponse] = useState([]);

  useEffect(() => {
    axios
      .get(`../../api/hours/${props.region}/${props.id}`)
      .then((res) => {
        setResponse(res.data);
      })
      .catch((error) => {
        console.error("Post.tsx error:", error);
      });
  }, []);

  return (
    <>
      <Head>
        <title>{props.id} - LoL Hours</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>{props.region}</h1>
      <h1>{props.id}</h1>
      <h1>{JSON.stringify(response)}</h1>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { region, id } = context.params!;
  return {
    props: {
      region,
      id,
    },
  };
};
